provider "fortios" { }


module "fg1-vpn" {

    source                = "./modules/ipsec_vpn"
    
    ### IPsec VPN Phase1-interface 설정
    name                  = "fg1-vpn"
    interface             = "wan1"
    proposal_phase1       = "aes256-sha1"  # default = aes128-sha256 aes256-sha256 aes128-sha1 aes256-sha1
    remote_gw             = "1.1.2.2"
    psksecret	          = "PreSharedKey"
#   ike_version           = "2"            # default = 1
#   keylife               = "28800"        # default = 86400
#   mode                  = "main"         # default = main
#   peertype              = "any"          # default = any
#   net_device	          = "disable"      # default = disable
#   dpd                   = "on-idle"      # default = on-demand  
#   dhgrp_phase1          = "2"            # default = 14 5
#   nattraversal          = "enable"       # default = enable
#   dpd_retryinterval     = "10"           # default = 20
    
    ### IPsec VPN Phase2-interface 설정
    proposal_phase2       = "aes256-sha1"
    auto_negotiate        = "enable"       # default = disable
#   pfs	                  = "enable"       # default = enable
#   dhgrp_phase2          = "2"            # default = 14 5
#   replay                = "enable"       # default = enable
#   keepalive             = "disable"      # default = disable
#   keylifeseconds        = "27000"        # default = 43200

    ### System Interface 설정
    vdom                  = "root"         # default = "root"
    ip                    = "2.2.1.1 255.255.255.255"
    remote_ip             = "2.2.1.2 255.255.255.252"
    allowaccess           = "ping"         # default = unset allowaccess
#   tcp_mss               = "1350"         # default = 0
#   mtu_override          = "disable"      # default = disable
#   mtu                   = "1500"         # default = 1500
#   autogenerated         = "on"           # required
}

module "vlan10" {
    source                = "./modules/interface"

    name                  = "vlan10"
    vdom                  = "root"         # default = "root"
    device_identification = "enable"
    role                  = "lan"
    interface             = "internal1"
    vlanid                = "10"           # range   = 1 - 4094
}

module "vlan20" {
    source                = "./modules/interface"

    name                  = "vlan20"
    vdom                  = "root"         # default = "root"
    device_identification = "enable"
    role                  = "lan"
    interface             = "internal1"
    vlanid                = "20"           # range   = 1 - 4094
}

module "vxlan10" {
    source                = "./modules/vxlan"

    name                  = "vxlan.10"
    interface             = "fg1-vpn"
    vni                   = "10"
    remote_ip             = "2.2.1.2"
    dependson             = "fortios_system_interface.vlan10"
}

module "vxlan20" {
    source                = "./modules/vxlan"

    name                  = "vxlan.20"
    interface             = "fg1-vpn"
    vni                   = "20"
    remote_ip             = "2.2.1.2"
    dependson             = "fortios_system_interface.vlan20"
}