variable "vdom" {
  description = "The name of the VDOM."
  type        = string
  default     = "root"
}

variable "name" {
  description = "The name of the IPsec VPN interface."
  type        = string
  default     = null
}

variable "device_identification" {
  description = "이 인터페이스에 연결된 네트워크의 장치에 대한 장치 ID 정보의 수동적 수집을 활성화/비활성화합니다."
  type        = string
  default     = null
}

variable "role" {
  description = "인터페이스 역할. 유효한 값 = lan, wan, dmz, undefined"
  type        = string
  default     = null
}

variable "interface" {
  description = "Interface name."
  type        = string
  default     = null
}

variable "vlanid" {
  description = "VLAN ID (1 - 4094)"
  type        = string
  default     = null
}



variable "ip" {
  type        = string
  default     = null
}

variable "remote_ip" {
  type        = string
  default     = null
}

variable "allowaccess" {
  type        = string
  default     = null
}



variable "tcp_mss" {
  type        = string
  default     = "0"
}

variable "mtu_override" {
  type        = string
  default     = "disable"
}

variable "mtu" {
  type        = string
  default     = null
}


variable "autogenerated" {
  type        = string
  default     = null
}

variable "dependson" {
  type        = string
  default     = null
}